Added drivers for Linux and Windows, and polished up the node script

diff --git a/selenium/_common b/selenium/_common
--- a/selenium/_common
+++ b/selenium/_common
@@ -15,24 +15,22 @@ function _assert-selenium-server-not-running(){
     # SEL_JOB_COUNT will be 1 if Selenium Server is already running on this machine
     SEL_JOB_COUNT="$(ps -f | grep java.*jar.*selenium-server.* | grep -v grep | wc -l)"
 
-    if [ ${SEL_JOB_COUNT} != 0 ]; then
-        echo "Selenium Server is already running, won't attempt to start"
+    if [ ! ${SEL_JOB_COUNT} -eq "0" ]; then
+        echo "Error: Selenium server is already running on this machine."
         return 1
     fi
-
-    return 0
 }
 
 ###
 # Start a Selenium Server node instance. A node is registered to the Hub, and executes in-browser tests.
 ###
 function launch-selenium-node(){
-    if [[ _assert-selenium-server-not-running -eq 1 ]]; then return 1; fi
+    _assert-selenium-server-not-running || return 1;
 
     SYSTEM=$1 #Must be the name of one of the subdirectories of selenium/driver; specifies the type of system for a node
 
     # browser flag arguments to be passed to the selenium server. E.G. "-browser browserName=safari -browser browserName=opera"
-    # to register a node that can run tests in either Safari or Opera. This parameter is only necessary if ROLE is "node"
+    # to register a node that can run tests in either Safari or Opera.
     BROWSERS=$2
 
     HUB_IP=192.168.33.11 # This should be the same as the IP address configured in the private_network configuration line of Vagrantfile
@@ -52,8 +50,7 @@ function launch-selenium-node(){
 # Start a Selenium Server hub instance. A hub registers nodes, and dispatches tests to them for execution.
 ###
 function launch-selenium-hub(){
-    _assert-selenium-server-not-running && return 1;
-
+    _assert-selenium-server-not-running || return 1;
     _launch-selenium-server "" "-role hub"
 }
 
diff --git a/selenium/node b/selenium/node
--- a/selenium/node
+++ b/selenium/node
@@ -10,4 +10,25 @@
 # get the directory in which this script is stored
 DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 source ${DIR}/_common
-launch-selenium-node mac64 "-browser browserName=chrome,maxInstances=3 -browser browserName=firefox,maxInstances=3"
+
+# Param 1: A browser argument like "-browser browserName=chrome,maxInstances=3 -browser browserName=firefox,maxInstances=3"
+BROWSER=$1
+if [[ "$BROWSER" == "" ]]; then
+    echo "Missing browser definition - eg \`node \"-browser browserName=chrome\"\`";
+    exit 1;
+fi
+
+# Determine what system we are running in. We currently don't test for 32 vs 64 bit systems - we just assume Mac is 64
+# bit, and Windows/Linux are 32. That's just a pragmatic decision - if there is a need we can add additional drivers
+# and add sniffing for 32 vs 64 bit.
+UNAME=$( uname -s )
+if [[ "$UNAME" == "Darwin" ]]; then
+    SYSTEM="mac64"
+elif [[ "$UNAME" == "Linux" ]]; then
+    SYSTEM="linux32"
+else
+    # For the time being we are simply assuming you're in Windows if one of the above cases doesn't apply.
+    SYSTEM="win32"
+fi
+
+launch-selenium-node ${SYSTEM} "${BROWSER}"
